workflows:
  react-native-expo-android:
    name: TN Happy Kids - Android Debug APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          cd my-expo-app
          npm install
          npx expo install expo-build-properties expo-splash-screen
      - name: Expo Prebuild
        script: |
          cd my-expo-app
          npx expo prebuild --platform android
      - name: Build Debug APK
        script: |
          cd my-expo-app/android
          ./gradlew assembleDebug
    artifacts:
      - my-expo-app/android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - dineshwebdev2003@gmail.com
